# Site settings
title:          Tech Dissect
description:    "My thoughts on what's new in Computer Science"
url:            "https://an-malik.github.io"

# Author
author:
  name:         Anurag
  url:          
  email:        amalik1223@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
